/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import class_thucthe.DSThongKeTruyenMuonNhieu23;
import dao.ThongKeTruyenMuonNhieuDAO23;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ThongKeTruyenMuonNhieuFrm23 extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeTruyenMuonNhieuFrm23
     */
    public ThongKeTruyenMuonNhieuFrm23() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNgayBatDau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNgayKetThuc = new javax.swing.JTextField();
        btnThongKe = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongKeTruyenMuonNhieu = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("THONG KE TRUYEN MUON NHIEU");

        jLabel2.setText("Ngày bắt đầu:");

        jLabel3.setText("Ngày kết thúc:");

        textNgayKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNgayKetThucActionPerformed(evt);
            }
        });

        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        tblThongKeTruyenMuonNhieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", "", "", ""},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Tác giả", "NXB", "Năm XB", "Tổng SL mượn", "Tổng tiền"
            }
        ));
        tblThongKeTruyenMuonNhieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongKeTruyenMuonNhieuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblThongKeTruyenMuonNhieu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThongKe)
                        .addGap(352, 352, 352))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(btnThongKe)
                .addGap(82, 82, 82)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNgayKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNgayKetThucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNgayKetThucActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date startDate = null;
        Date endDate = null;
        try{
            startDate = sdf.parse(txtNgayBatDau.getText());
            endDate = sdf.parse(textNgayKetThuc.getText());

        }catch (Exception e){
            
        }
        
        if(startDate.after(endDate)){
            JOptionPane.showMessageDialog(this, "Vui long nhap lai ngay!");
        }
        else{
            ThongKeTruyenMuonNhieuDAO23 dao = new ThongKeTruyenMuonNhieuDAO23();
        ArrayList<DSThongKeTruyenMuonNhieu23> result = dao.getDSThongKeTruyenMuonNhieu(startDate, endDate);
        if(result.size()==0){
            JOptionPane.showMessageDialog(this, "Chua co truyen nao duoc muon!");
        }
        else{
            DefaultTableModel model = (DefaultTableModel) tblThongKeTruyenMuonNhieu.getModel();
              model.setRowCount(0);
              int totalQuantity=0;
              float totalMoney=0;
              
             for (DSThongKeTruyenMuonNhieu23 item : result) {
             Object[] row = {item.getMaDauTruyen(), item.getTenTruyen(), item.getTenTacGia(), 
                        item.getNhaXuatBan(), item.getNamXuatBan(), item.getTongSoLuongMuon(), 
                        item.getTongTien()};
             model.addRow(row);
             
             totalQuantity +=item.getTongSoLuongMuon();
             totalMoney +=item.getTongTien();
             
            }
            
             Object[] totalRow = {"Tổng", "", "", "", "", totalQuantity, totalMoney};
              model.addRow(totalRow);
        
        }
        }
        
        
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void tblThongKeTruyenMuonNhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongKeTruyenMuonNhieuMouseClicked

        int selectedRow = tblThongKeTruyenMuonNhieu.getSelectedRow();
    if (selectedRow != -1) {
        int maDauTruyen = (int) tblThongKeTruyenMuonNhieu.getValueAt(selectedRow, 0); // Lấy maDauTruyen từ cột đầu tiên
        String ngayBatDau = txtNgayBatDau.getText();
        String ngayKetThuc = textNgayKetThuc.getText();
        
        ChiTietHoaDonFrm myFrame = new ChiTietHoaDonFrm(maDauTruyen, ngayBatDau, ngayKetThuc);
        myFrame.setVisible(true);
    }
    }//GEN-LAST:event_tblThongKeTruyenMuonNhieuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeTruyenMuonNhieuFrm23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeTruyenMuonNhieuFrm23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeTruyenMuonNhieuFrm23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeTruyenMuonNhieuFrm23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeTruyenMuonNhieuFrm23().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblThongKeTruyenMuonNhieu;
    private javax.swing.JTextField textNgayKetThuc;
    private javax.swing.JTextField txtNgayBatDau;
    // End of variables declaration//GEN-END:variables
}
